/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.books.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Author service. Represents a row in the &quot;Books_Author&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.books.model.impl.AuthorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.books.model.impl.AuthorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Author
 * @generated
 */
@ProviderType
public interface AuthorModel extends BaseModel<Author>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a author model instance should use the {@link Author} interface instead.
	 */

	/**
	 * Returns the primary key of this author.
	 *
	 * @return the primary key of this author
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this author.
	 *
	 * @param primaryKey the primary key of this author
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this author.
	 *
	 * @return the uuid of this author
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this author.
	 *
	 * @param uuid the uuid of this author
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the author ID of this author.
	 *
	 * @return the author ID of this author
	 */
	public long getAuthorId();

	/**
	 * Sets the author ID of this author.
	 *
	 * @param authorId the author ID of this author
	 */
	public void setAuthorId(long authorId);

	/**
	 * Returns the group ID of this author.
	 *
	 * @return the group ID of this author
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this author.
	 *
	 * @param groupId the group ID of this author
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this author.
	 *
	 * @return the company ID of this author
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this author.
	 *
	 * @param companyId the company ID of this author
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the nom of this author.
	 *
	 * @return the nom of this author
	 */
	@AutoEscape
	public String getNom();

	/**
	 * Sets the nom of this author.
	 *
	 * @param nom the nom of this author
	 */
	public void setNom(String nom);

	/**
	 * Returns the prenom of this author.
	 *
	 * @return the prenom of this author
	 */
	@AutoEscape
	public String getPrenom();

	/**
	 * Sets the prenom of this author.
	 *
	 * @param prenom the prenom of this author
	 */
	public void setPrenom(String prenom);

	/**
	 * Returns the email of this author.
	 *
	 * @return the email of this author
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this author.
	 *
	 * @param email the email of this author
	 */
	public void setEmail(String email);

	/**
	 * Returns the date naissance of this author.
	 *
	 * @return the date naissance of this author
	 */
	public Date getDateNaissance();

	/**
	 * Sets the date naissance of this author.
	 *
	 * @param DateNaissance the date naissance of this author
	 */
	public void setDateNaissance(Date DateNaissance);

	/**
	 * Returns the date deces of this author.
	 *
	 * @return the date deces of this author
	 */
	public Date getDateDeces();

	/**
	 * Sets the date deces of this author.
	 *
	 * @param dateDeces the date deces of this author
	 */
	public void setDateDeces(Date dateDeces);

	/**
	 * Returns the autobiographie of this author.
	 *
	 * @return the autobiographie of this author
	 */
	@AutoEscape
	public String getAutobiographie();

	/**
	 * Sets the autobiographie of this author.
	 *
	 * @param autobiographie the autobiographie of this author
	 */
	public void setAutobiographie(String autobiographie);

}