/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.books.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Books service. Represents a row in the &quot;Books_Books&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.books.model.impl.BooksModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.books.model.impl.BooksImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Books
 * @generated
 */
@ProviderType
public interface BooksModel
	extends BaseModel<Books>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a books model instance should use the {@link Books} interface instead.
	 */

	/**
	 * Returns the primary key of this books.
	 *
	 * @return the primary key of this books
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this books.
	 *
	 * @param primaryKey the primary key of this books
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this books.
	 *
	 * @return the uuid of this books
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this books.
	 *
	 * @param uuid the uuid of this books
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the book ID of this books.
	 *
	 * @return the book ID of this books
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this books.
	 *
	 * @param bookId the book ID of this books
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the group ID of this books.
	 *
	 * @return the group ID of this books
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this books.
	 *
	 * @param groupId the group ID of this books
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this books.
	 *
	 * @return the company ID of this books
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this books.
	 *
	 * @param companyId the company ID of this books
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this books.
	 *
	 * @return the user ID of this books
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this books.
	 *
	 * @param userId the user ID of this books
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this books.
	 *
	 * @return the user uuid of this books
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this books.
	 *
	 * @param userUuid the user uuid of this books
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the title of this books.
	 *
	 * @return the title of this books
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this books.
	 *
	 * @param title the title of this books
	 */
	public void setTitle(String title);

	/**
	 * Returns the author ID of this books.
	 *
	 * @return the author ID of this books
	 */
	@AutoEscape
	public String getAuthorId();

	/**
	 * Sets the author ID of this books.
	 *
	 * @param authorId the author ID of this books
	 */
	public void setAuthorId(String authorId);

	/**
	 * Returns the conte_rendu of this books.
	 *
	 * @return the conte_rendu of this books
	 */
	@AutoEscape
	public String getConte_rendu();

	/**
	 * Sets the conte_rendu of this books.
	 *
	 * @param conte_rendu the conte_rendu of this books
	 */
	public void setConte_rendu(String conte_rendu);

	/**
	 * Returns the create date of this books.
	 *
	 * @return the create date of this books
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this books.
	 *
	 * @param createDate the create date of this books
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the date publication of this books.
	 *
	 * @return the date publication of this books
	 */
	public Date getDatePublication();

	/**
	 * Sets the date publication of this books.
	 *
	 * @param datePublication the date publication of this books
	 */
	public void setDatePublication(Date datePublication);

	/**
	 * Returns the modified date of this books.
	 *
	 * @return the modified date of this books
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this books.
	 *
	 * @param modifiedDate the modified date of this books
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the prix achat of this books.
	 *
	 * @return the prix achat of this books
	 */
	public double getPrixAchat();

	/**
	 * Sets the prix achat of this books.
	 *
	 * @param prixAchat the prix achat of this books
	 */
	public void setPrixAchat(double prixAchat);

	/**
	 * Returns the prix vente of this books.
	 *
	 * @return the prix vente of this books
	 */
	public double getPrixVente();

	/**
	 * Sets the prix vente of this books.
	 *
	 * @param prixVente the prix vente of this books
	 */
	public void setPrixVente(double prixVente);

}